export class FlightDetail {
    id: string = "";
    roundTrip: number = 0;
    depart: string = "";
    departTime: string = "";
    departAirport: string = "";
    return: string = "";
    returnTime: string = "";
    returnAirport: string = "";
    stops: FlightDetail[] = [];
    totalTime: string = "";
    classType: string = "";
    departAirlinePicture: string = "";
    departAirlineName: string = "";
    departAirlinePlane: string = "";
    returnAirlinePicture: string = "";
    returnAirlineName: string = "";
    returnAirlinePlane: string = "";
    totalMoney: number = 0;
}
